# Generated by Django 3.2.2 on 2021-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('home', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10)),
                ('hakbun', models.CharField(max_length=2)),
                ('dream', models.CharField(max_length=20)),
                ('food', models.CharField(max_length=10)),
            ],
        ),
    ]
