# Generated by Django 3.2.2 on 2021-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dream',
        ),
        migrations.RemoveField(
            model_name='team',
            name='food',
        ),
    ]
