# Generated by Django 3.2.2 on 2021-05-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_team_hakbun'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lover',
            field=models.CharField(default='', max_length=10),
        ),
    ]
