# Generated by Django 3.2.2 on 2021-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_team_lover'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dream',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='food',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='sul',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='birthday',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='hakbun',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='home',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='major',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='residence',
            field=models.CharField(default='', max_length=10),
        ),
    ]
