# Generated by Django 3.2.2 on 2021-05-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albamon_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='place',
        ),
    ]
