# Generated by Django 3.2.2 on 2021-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albamon_app', '0002_remove_job_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(default=8720),
        ),
    ]
