# Generated by Django 3.2.2 on 2021-05-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albamon_app', '0004_auto_20210522_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
