# Generated by Django 3.2.2 on 2021-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albamon_app', '0010_auto_20210522_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(default=8520),
        ),
    ]
