# Generated by Django 3.2.2 on 2021-05-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albamon_app', '0011_alter_job_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='information',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='work',
            field=models.TextField(default='', max_length=100),
        ),
    ]
