# Generated by Django 3.2.2 on 2021-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albamon_app', '0015_alter_job_applier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(),
        ),
    ]
